# Generated by Django 3.1.3 on 2020-11-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='variant',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='BikeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(blank=True, max_length=255)),
                ('cooling_system', models.CharField(blank=True, max_length=100)),
                ('power', models.CharField(blank=True, max_length=100)),
                ('torque', models.CharField(blank=True, max_length=100)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('wheels', models.CharField(blank=True, max_length=100)),
                ('transmission', models.CharField(blank=True, max_length=100)),
                ('no_of_gears', models.CharField(blank=True, max_length=100)),
                ('brake_front', models.CharField(blank=True, max_length=100)),
                ('brake_rear', models.CharField(blank=True, max_length=100)),
                ('suspension_front', models.CharField(blank=True, max_length=255)),
                ('suspension_rear', models.CharField(blank=True, max_length=255)),
                ('body_type', models.CharField(blank=True, max_length=100)),
                ('ABS', models.CharField(blank=True, max_length=100)),
                ('console', models.CharField(blank=True, max_length=100)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes_app.bikes')),
            ],
        ),
    ]
