# Generated by Django 3.1.3 on 2020-11-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes_app', '0002_auto_20201126_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
