# Generated by Django 3.1.3 on 2020-11-26 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes_app', '0003_auto_20201126_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikedetails',
            name='bike',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bikes_app.bikes'),
        ),
    ]
